server {
    listen       80;
    server_name  localhost;

    # Increase header and cookie size limits
    large_client_header_buffers 4 32k;
    client_header_buffer_size 8k;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
